DELETE  https://go-api-69re.onrender.com/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ldzJAZXhhbXBsZS5jb20iLCJleHAiOjE3NDEwMjAyODQsInVzZXJJZCI6Mn0.fzAx2Fii_Xynsao_Kn-6nWm-J1D39EHXKJXbHqJ57oU

