PUT  https://go-api-69re.onrender.com/events/1
content-type: application/json

{
    "name": "John Doe 2",
    "description": "A test event 2",
    "location": "A test location 2",
    "dateTime": "2025-01-01T15:30:00.000Z"
}

